### ISSUE TITLE
Doesn't install on Statamic 4

### ISSUE THREAD

**Issue by GuyVervillePerso** [goellner/statamic-3-table-on-steroids#1]
Hi,
Your addon does not install on Statamic 4. Is it just a version issue?

**Comment by goellner** [comment]
will take a look this week and publish a new release

**Comment by goellner** [comment]
published a new release

**Comment by GuyVervillePerso** [comment]
Thank you! It installed perfectly. However, I would suggest an improvement. My client wish is to be able to select columns in an Excel sheet and to copy it in a plugin like yours. But Copy/Paste from Excel creates a tab separated data... It would be great to being able to tell the plugin which delimiter to use :-)

**Comment by St3Ko** [comment]
@GuyVervillePerso the new 1.3.0 release now supports custom delimiters and tab separated data. Please let us know if this works for you 🙂

**Comment by GuyVervillePerso** [comment]
Many, many thanks!

However, please note that French Excel uses “,” for decimal point. So even if we use the tab delimiter, your plugin translate everything into “,” and is unable to process afterwards…

When delimiter is set to “TAB”, the plugin should make sure that what is between is not changed.

For example, this original doesn’t not work:
2022-03-31     2022-06-30     2022-09-30     2022-12-31
55,00%           48,75%           46,75%           51,75%
100,00%         75,00%           75,00%           87,00%
120,00%         120,00%         112,00%         120,00%
22,00%           22,00%           0,00%  22,00%
110,00%         110,00%         0,00%  110,00%
33,00%           0,00%  0,00%  16,50%
110,00%         0,00%  0,00%  0,00%
110,00%         0,00%  0,00%  110,00%
110,00%         70,75%           46,75%           90,25%
10,00%           10,00%           10,00%           10,00%
11,00%           7,08%  4,68%  9,03%

Guy

De : Stefan Koller ***@***.***>
Date : jeudi, 3 août 2023 à 05:12
À : goellner/statamic-3-table-on-steroids ***@***.***>
Cc : Guy Verville ***@***.***>, Mention ***@***.***>
Objet : Re: [goellner/statamic-3-table-on-steroids] Doesn't install on Statamic 4 (Issue #1)

@GuyVervillePerso<https://github.com/GuyVervillePerso> the new 1.3.0 release now supports custom delimiters and tab separated data. Please let us know if this works for you 🙂

**Comment by GuyVervillePerso** [comment]
This was supposed to be attached to my previous comment.
***@***.***

De : Stefan Koller ***@***.***>
Date : jeudi, 3 août 2023 à 05:12
À : goellner/statamic-3-table-on-steroids ***@***.***>
Cc : Guy Verville ***@***.***>, Mention ***@***.***>
Objet : Re: [goellner/statamic-3-table-on-steroids] Doesn't install on Statamic 4 (Issue #1)

@GuyVervillePerso<https://github.com/GuyVervillePerso> the new 1.3.0 release now supports custom delimiters and tab separated data. Please let us know if this works for you 🙂

**Comment by St3Ko** [comment]
@GuyVervillePerso version 1.3.1 was just released. This should now be fixed.

**Comment by GuyVervillePerso** [comment]
Thank you very much! It works and my client is very pleased!

Guy

De : Stefan Koller ***@***.***>
Date : jeudi, 3 août 2023 à 09:47
À : goellner/statamic-3-table-on-steroids ***@***.***>
Cc : Guy Verville ***@***.***>, Mention ***@***.***>
Objet : Re: [goellner/statamic-3-table-on-steroids] Doesn't install on Statamic 4 (Issue #1)

@GuyVervillePerso<https://github.com/GuyVervillePerso> version 1.3.1 was just released. This should now be fixed.
